### PR TITLE
UPDATE

### PR DESCRIPTION
**Pull request by khusika**
config_wifi_dual_band_support has been defined https://github.com/MSM8916-Samsung/android_device_samsung_a5-common/blob/cm-12.1/overlay/frameworks/base/core/res/res/values/config.xml#L151
config_automatic_brightness_available has been defined https://github.com/CyanogenMod/android_device_samsung_qcom-common/blob/cm-12.1/overlay/frameworks/base/core/res/res/values/config.xml#L27

### CODE REVIEW

**Comment by TheWhisp** [comment]
I use a forked qcom-common which does not set that overlay (https://github.com/MSM8916-Samsung/android_local_manifest/commit/69f79c9bb508bff1a00dffd9bcce27dcceb716a8)

**Comment by khusika** [comment]
As i know,config_automatic_brightness_available has been enabled by default in the samsung qcom-common and A5 support with this too... and why you remove config_automatic_brightness_available from the samsung qcom-common?

I think, it will be better to use samsung qcom-common from CM without any changes
then, if any other msm8916 devices which it does not have light sensor, let the device-tree set it "false"

**Comment by TheWhisp** [comment]
I agree, but for some reason it did not work for my other device when I set it to "false", it still picked up the overlay from common repo

**Comment by khusika** [comment]
Even CM dev wont merge this 🙈
http://review.cyanogenmod.org/#/c/
113988/
I'll try to make it false inside tree(my own device) 😆

**Comment by khusika** [comment]
It automatically set to false, even in the samsung qcom-common set true
So, +1 for this commit :+1: 

screenshot from 2015-10-20 04 32 38

**Comment by khusika** [comment]
Good to go @TheWhisp :+1:

**Comment by TheWhisp** [comment]
I don't see any reason disabling block based ota

**Pull request closed without merging**
